import json
import json_repair
import logging
import re
from typing import Callable, Dict, List

from app.core.config import settings
from app.core.llm_client import get_llm_client
from app.core.provider_credentials import get_minimax_llm_model
from app.services.document_parser import detect_ppt_sources
from app.services.search_service import get_knowledge_augmenter
from app.utils.text_cleaning import normalize_markdown_emphasis

logger = logging.getLogger(__name__)


def _clean_json_response(content: str) -> str:
    """从 LLM 响应中提取 JSON 数组。"""
    content = re.sub(r"^```(?:json)?\s*|```$", "", content, flags=re.MULTILINE | re.IGNORECASE).strip()
    start_idx = content.find("[")
    end_idx = content.rfind("]")
    if start_idx != -1 and end_idx != -1:
        content = content[start_idx : end_idx + 1]
    return content


def _is_strict_page_count_request(topic: str) -> bool:
    text = topic or ""
    strict_patterns = (
        r"必须\s*\d+\s*页",
        r"严格\s*\d+\s*页",
        r"固定\s*\d+\s*页",
        r"只能\s*\d+\s*页",
        r"不要超过\s*\d+\s*页",
        r"不超过\s*\d+\s*页",
        r"exactly\s+\d+\s+pages?",
        r"must\s+be\s+\d+\s+pages?",
    )
    return any(re.search(pattern, text, flags=re.IGNORECASE) for pattern in strict_patterns)


def _soft_page_bounds(page_count: int) -> tuple[int, int]:
    target = max(1, int(page_count or 1))
    lower = max(1, int(target * 0.7))
    upper = max(target, int(target * 1.3 + 0.999)) + 1
    return lower, upper


def _is_ppt_transform_request(topic: str) -> bool:
    text = (topic or "").lower()
    patterns = (
        r"扩展到\s*\d+\s*页",
        r"拓展到\s*\d+\s*页",
        r"缩减到\s*\d+\s*页",
        r"压缩到\s*\d+\s*页",
        r"减少到\s*\d+\s*页",
        r"提取",
        r"融合",
        r"合并",
        r"重组",
        r"改写",
        r"重新规划",
        r"只要",
        r"某个主题",
        r"特定主题",
        r"expand to\s+\d+\s+pages?",
        r"reduce to\s+\d+\s+pages?",
        r"extract",
        r"merge",
        r"combine",
    )
    return any(re.search(pattern, text, flags=re.IGNORECASE) for pattern in patterns)


def infer_page_count_from_single_ppt(documents: str, topic: str = "") -> int | None:
    sources = detect_ppt_sources(documents)
    if len(sources) != 1 or _is_ppt_transform_request(topic):
        return None
    pages = int(sources[0].get("pages") or 0)
    return pages if pages > 0 else None


def _normalize_outline_page_count(outline: List[Dict], page_count: int, strict_page_count: bool = False) -> List[Dict]:
    """Keep LLM output reasonable while treating page_count as a soft target by default."""
    if not isinstance(outline, list):
        raise ValueError("Content plan generation failed: LLM output is not a JSON array")
    target_count = max(1, int(page_count or len(outline) or 1))
    max_count = target_count if strict_page_count else _soft_page_bounds(target_count)[1]
    if len(outline) > max_count:
        logger.warning(
            f"ContentPlan: LLM returned {len(outline)} pages, trimming to max {max_count} "
            f"(target={target_count}, strict={strict_page_count})"
        )
        outline = outline[:max_count]
    for idx, page in enumerate(outline, start=1):
        if isinstance(page, dict):
            page["page_num"] = idx
    return outline


def _normalize_content_markdown(outline: List[Dict]) -> List[Dict]:
    """Normalize Markdown generated by the LLM before it becomes project state."""
    for page in outline:
        if not isinstance(page, dict):
            continue
        text_content = page.get("text_content")
        if isinstance(text_content, dict):
            for key in ("headline", "subhead", "body"):
                value = text_content.get(key)
                if isinstance(value, str):
                    text_content[key] = normalize_markdown_emphasis(value)
                elif isinstance(value, list):
                    text_content[key] = [
                        normalize_markdown_emphasis(item) if isinstance(item, str) else item
                        for item in value
                    ]
        notes = page.get("speaker_notes")
        if isinstance(notes, str):
            page["speaker_notes"] = normalize_markdown_emphasis(notes)
        _normalize_punchline_page_content(page)
    return outline


def _first_text_line(value) -> str:
    if isinstance(value, list):
        candidates = [str(item) for item in value if str(item).strip()]
    else:
        candidates = str(value or "").splitlines()
    for line in candidates:
        cleaned = re.sub(r"^\s*(?:[-*]|\d+[.)])\s*", "", str(line)).strip()
        cleaned = normalize_markdown_emphasis(cleaned).strip()
        if cleaned:
            return cleaned
    return ""


def _normalize_punchline_page_content(page: Dict) -> None:
    """Keep hero/quote slides as punchline slides, not lightweight content slides."""
    page_type = str(page.get("type") or "").strip().lower()
    if page_type not in {"hero", "quote"}:
        return

    text_content = page.get("text_content")
    if not isinstance(text_content, dict):
        return

    headline = _first_text_line(text_content.get("headline"))
    subhead = _first_text_line(text_content.get("subhead"))
    body = text_content.get("body")
    body_line = _first_text_line(body)

    if not headline and body_line:
        headline = body_line

    body_text = "\n".join(str(x) for x in body) if isinstance(body, list) else str(body or "")
    if body_text.strip():
        notes = str(page.get("speaker_notes") or "").strip()
        preserved = f"原金句页正文素材：{normalize_markdown_emphasis(body_text.strip())}"
        page["speaker_notes"] = f"{notes}\n\n{preserved}".strip() if notes else preserved

    text_content["headline"] = headline
    text_content["subhead"] = subhead
    text_content["body"] = ""

    suggestion = str(page.get("visual_suggestion") or "").strip()
    if not suggestion or any(term in suggestion for term in ("内容页", "信息图", "列表", "要点")):
        page["visual_suggestion"] = (
            "真正的金句页：只突出一句话、一个短语或一个词；"
            "可走引用、口号、结论、转场判断、数据洞察等方向，"
            "视觉用克制背景、象征物、人物/场景或纯色纹理承托，"
            "必须沿用整套 PPT 的配色、字体气质和材质语言。"
        )


def generate_content_plan(
    topic: str,
    audience: str = "通用受众",
    page_count: int = 10,
    documents: str = "",
    on_progress: Callable[[dict], None] | None = None,
) -> List[Dict]:
    """
    根据主题和文档生成 Content Plan。
    支持流式读取和进度回调，让前端能看到生成过程。
    """
    has_docs = bool(documents and documents.strip())
    strict_page_count = _is_strict_page_count_request(topic)
    min_pages, max_pages = (page_count, page_count) if strict_page_count else _soft_page_bounds(page_count)
    logger.info(
        f"ContentPlan: 为主题 '{topic[:30]}...' 生成大纲, "
        f"page_count={page_count}, has_documents={has_docs}"
    )

    if on_progress:
        on_progress({"stage": "analyzing", "message": "正在分析主题和文档素材..."})

    doc_section = ""
    if has_docs:
        ppt_sources = detect_ppt_sources(documents)
        ppt_policy = ""
        if len(ppt_sources) == 1:
            ppt = ppt_sources[0]
            ppt_policy = f"""
【上传 PPT 的特殊处理】
系统识别到用户上传了 1 个 PPT：{ppt.get("filename") or "未命名 PPT"}，原始页数 {ppt.get("pages")} 页。
- 如果用户没有明确要求扩展、缩减、提取特定主题、融合或重组，你必须按原 PPT 逐页复刻内容结构：输出页数等于 {ppt.get("pages")} 页，第 i 个 JSON 页面对应原 PPT 第 i 页。
- 逐页复刻时，文字内容应尽量保留原页标题、要点、数据和备注，不要压缩成摘要，也不要重新发明叙事。
- 如果用户明确要求扩展/缩减/提取/融合/加入新想法，则按用户意图动态调整页数和结构。
"""
        elif len(ppt_sources) > 1:
            ppt_policy = """
【上传多个 PPT 的特殊处理】
系统识别到用户上传了多个 PPT。不要机械相加页数；先理解用户意图：融合、提取、重组、对比或加入新想法。除非用户指定页数，否则按内容逻辑生成合适页数。
"""
        doc_section = f"""
【用户上传的文档素材】
{documents}

【文档使用规则】
1. 以上文档是用户提供的核心素材，你必须基于文档内容设计 PPT 大纲。
2. 文档中的关键论点、数据、结构必须体现在大纲中。
3. 页数是软目标，不一定严格限制在 {page_count} 页；如果拆页能显著提升叙事和视觉表达，可在 {min_pages}-{max_pages} 页范围内调整。
{ppt_policy}
"""

    # 【新增】内容规划阶段也触发实时搜索，避免模型对前沿话题产生幻觉
    search_section = ""
    search_context = get_knowledge_augmenter().augment(topic, has_documents=has_docs)
    if search_context:
        search_section = f"""
{search_context}

【搜索结果使用规则】
1. 上述网络搜索结果是实时获取的，你必须基于这些事实信息设计 PPT 大纲。
2. 人名、角色名、剧情、数据等关键信息必须与搜索结果一致，严禁编造。
3. 如果搜索结果不足以支撑完整大纲，可以合理推断，但必须标注为"推测"。
"""
        logger.info(f"ContentPlan: 已注入搜索上下文，topic={topic[:30]}")

    prompt = f"""你是一位顶尖的商业演示架构师。请为以下主题设计一份 PPT 大纲。

【主题】
{topic}

【背景】
- 目标受众: {audience}
- 期望页数: {"必须 " + str(page_count) + " 页" if strict_page_count else f"{page_count} 页左右，可在 {min_pages}-{max_pages} 页范围内浮动"}
{doc_section}
{search_section}

【任务要求】
1. 设计清晰的叙事结构（起承转合）。
2. 每页必须包含：
   - page_num: 页码
   - type: 页面类型（cover/目录 toc/content/hero/data/ending）。其中 hero 是“金句页/punchline slide”，不是普通内容页。
   - section_title: 所属章节
   - text_content.headline: 大标题（有力、简洁的断言句）
   - text_content.subhead: 副标题（可选）
   - text_content.body: 正文（markdown 格式字符串，支持加粗、列表、表格等）
     **格式选择原则：格式服从认知，不要为整齐而整齐。**
     判断标准是——读者看这页时，大脑在做什么操作？
     - **需要横向对比不同维度**（如"过去 vs 现在"、"维度/关键词/误区"）→ 用表格，让读者一眼对齐差异。
     - **需要按顺序接收独立要点**（如"四个建议"、"今日议题"）→ 用编号列表或 bullet + 加粗引导，让读者快速扫读。
     - **需要沉浸理解叙事逻辑**（如因果推导、故事展开）→ 用段落文字，保持阅读流畅。
     不要为了"结构化"而硬套表格。表格是认知工具，不是装饰；宁可用干净的列表，也不要把单维度内容强行切成两列表格。
   - speaker_notes: 演讲者备注（详细论述，供演讲者参考）
   - visual_suggestion: 画面/配图建议
3. 封面和封底各占一页。
4. 内容页不要堆砌，每页只说一件事。
5. 标题多用设问或断言，少平铺直叙。
6. 如果一个页面同时包含多个强画面证据/大事件，请主动拆页，而不是硬塞进同一页。例如：白皮书发布会、名企合作、直播间/达人矩阵、资本价值、终端体验、B端团购等应优先独立成页。
7. 普通“期望页数/约 X 页”是软目标；只有用户明确说“必须/严格/固定/只能 X 页”时才严格等于 X 页。
8. 金句页（type="hero"）必须像真正的 punchline slide：
   - 只承载一句极短、有记忆点的话、一个短语或一个词；可以是名言/引用，也可以是口号、结论、转场判断、数据洞察、用户原话、核心命题。
   - text_content.headline 放金句本身；text_content.subhead 只在确有必要时放来源/场景/轻量解释；text_content.body 必须为空字符串。
   - 不要把三条建议、解释段落、普通论点伪装成金句页；这些应保持 content/data 页。
   - visual_suggestion 要体现金句页的停顿感和记忆点，但不要固定成某一种形式；必须沿用整套 PPT 的配色和字体气质。

【JSON 格式】
严格输出 JSON 数组，不要包含 Markdown 代码块标记：
[
  {{
    "page_num": 1,
    "type": "cover",
    "section_title": "",
    "text_content": {{
      "headline": "主标题",
      "subhead": "副标题",
      "body": ""
    }},
    "speaker_notes": "",
    "visual_suggestion": ""
  }}
]
"""

    client = get_llm_client()
    stream = client.chat.completions.create(
        model=get_minimax_llm_model(),
        messages=[
            {"role": "system", "content": "你是世界一流的 PPT 架构师。必须且只能输出合法的 JSON 数组，严禁添加任何额外说明文本。"},
            {"role": "user", "content": prompt},
        ],
        temperature=0.5,
        stream=True,
    )

    full_content = ""
    page_count_found = 0
    in_think = False
    think_buffer = ""

    if on_progress:
        on_progress({"stage": "generating", "message": "正在构建叙事结构...", "current_page": 0, "total_pages": max_pages})

    for chunk in stream:
        if not chunk.choices:
            continue
        delta = chunk.choices[0].delta.content or ""
        full_content += delta

        # 提取 think 内容（MiniMax 的推理过程）
        buf = delta
        while buf:
            if not in_think:
                idx = buf.find("<think>")
                if idx == -1:
                    buf = ""
                    break
                buf = buf[idx + 7:]
                in_think = True
            else:
                idx = buf.find("</think>")
                if idx == -1:
                    think_buffer += buf
                    buf = ""
                    break
                else:
                    think_buffer += buf[:idx]
                    buf = buf[idx + 8:]
                    in_think = False

        # 检测新生成的页面
        new_page_count = full_content.count('"page_num"')
        if new_page_count > page_count_found:
            page_count_found = new_page_count
            if on_progress:
                current_page = min(page_count_found, max_pages)
                on_progress({
                    "stage": "generating",
                    "message": f"正在生成第 {current_page}/{max_pages} 页...",
                    "current_page": current_page,
                    "total_pages": max_pages,
                    "think": think_buffer[-200:] if think_buffer else None,
                })

    # 去掉 think 标签后解析 JSON
    clean = re.sub(r"<think>.*?</think>", "", full_content, flags=re.DOTALL).strip()
    clean = _clean_json_response(clean)

    # 多层降级解析：先尝试 json_repair，再尝试标准 json
    outline = None
    parse_errors = []

    try:
        outline = json_repair.loads(clean)
    except Exception as e:
        parse_errors.append(f"json_repair: {e}")

    if outline is None:
        try:
            outline = json.loads(clean)
        except Exception as e:
            parse_errors.append(f"json.loads: {e}")

    if outline is None:
        # 最后的尝试：只提取第一个完整对象到最后一个完整对象之间的内容
        first_obj = clean.find("{")
        last_arr = clean.rfind("]")
        if first_obj != -1 and last_arr != -1 and first_obj < last_arr:
            snippet = "[" + clean[first_obj:last_arr + 1].replace("}\n{", "},\n{") + "]"
            try:
                outline = json_repair.loads(snippet)
            except Exception as e:
                parse_errors.append(f"snippet repair: {e}")

    if outline is None:
        preview = clean[:500].replace("\n", " ")
        logger.error(f"[ContentPlan] JSON parse failed after all fixes. Preview: {preview!r}")
        logger.error(f"[ContentPlan] Errors: {'; '.join(parse_errors)}")
        raise ValueError(f"Content plan generation failed: invalid JSON from LLM. Preview: {preview[:200]}")

    outline = _normalize_outline_page_count(outline, page_count, strict_page_count=strict_page_count)
    outline = _normalize_content_markdown(outline)

    logger.info(f"ContentPlan: 生成完成，共 {len(outline)} 页")

    if on_progress:
        on_progress({"stage": "saving", "message": "正在保存结果...", "current_page": len(outline), "total_pages": len(outline)})

    return outline
