import logging
import os

import redis

from app.celery_app import celery_app
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.provider_credentials import load_task_provider_credentials, provider_credentials_context
from app.models.base import SessionLocal
from app.models.models import Project, Slide
from app.services.generation_pipeline import run_generation_pipeline
from app.services.run_state import finish_run, is_run_active, mark_run_running, update_run_progress
from app.services.style_proposal import generate_style_proposals
from app.services.image_analyzer import analyze_logo, analyze_reference_image
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

redis_client = redis.from_url(settings.REDIS_URL or "redis://localhost:6379/0")


def compute_style_asset_signature(project: Project | None) -> str:
    """Fingerprint global style assets so cached proposals are invalidated after uploads/deletes."""
    if not project:
        return ""
    parts = []
    for ref in sorted(project.reference_images or [], key=lambda r: (r.role or "", r.id or "")):
        if ref.slide_id or ref.role not in {"logo", "style_ref", "template"}:
            continue
        try:
            mtime = os.path.getmtime(ref.file_path) if os.path.exists(ref.file_path) else 0
        except OSError:
            mtime = 0
        parts.append({
            "id": ref.id,
            "role": ref.role,
            "path": os.path.basename(ref.file_path or ""),
            "mtime": round(mtime, 3),
        })
    if project.selected_template_recommendations:
        parts.append({"template_recommendations": project.selected_template_recommendations})
    return json_dumps_compact(parts) if parts else ""


def json_dumps_compact(value) -> str:
    import json
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _resolve_target_pages(project_id: str, page_nums: list = None) -> list:
    """Resolve which pages to generate. Returns list of page_num."""
    if page_nums:
        return list(page_nums)
    db = SessionLocal()
    try:
        slides = db.query(Slide).filter(Slide.project_id == project_id).order_by(Slide.page_num).all()
        return [s.page_num for s in slides if s.prompt_text]
    finally:
        db.close()


def _acquire_page_locks(project_id: str, page_nums: list, ttl: int = 600) -> list:
    """Try to acquire per-page locks. Returns list of page_nums that were successfully locked."""
    acquired = []
    for pn in page_nums:
        lock_key = f"project:{project_id}:slide:{pn}:generating"
        if redis_client.set(lock_key, "1", nx=True, ex=ttl):
            acquired.append(pn)
        else:
            logger.info(f"Page {pn} is already being generated by another task, skipping")
    return acquired


def _release_page_locks(project_id: str, page_nums: list):
    """Release per-page locks."""
    for pn in page_nums:
        redis_client.delete(f"project:{project_id}:slide:{pn}:generating")


def _cleanup_stale_generating_slides(project_id: str, page_nums: list):
    """Reset slide status for pages we couldn't lock (locked by another task)."""
    db = SessionLocal()
    try:
        slides = db.query(Slide).filter(
            Slide.project_id == project_id,
            Slide.page_num.in_(page_nums),
            Slide.status == "generating",
        ).all()
        for slide in slides:
            lock_key = f"project:{project_id}:slide:{slide.page_num}:generating"
            if not redis_client.exists(lock_key):
                slide.status = "prompt_ready"
                slide.error_msg = "生成任务已跳过：锁已过期"
        db.commit()
    except Exception as exc:
        db.rollback()
        logger.warning(f"Failed to cleanup stale generating slides: {exc}")
    finally:
        db.close()


@celery_app.task
def generate_slides_task(project_id: str, page_nums: list = None, prototype: bool = False, run_id: str = None, credential_id: str = None):
    """Celery task: 执行幻灯片生成流水线（页级别锁，允许不同页并发生成）。"""
    credentials = load_task_provider_credentials(redis_client, credential_id)
    with provider_credentials_context(credentials):
        return _generate_slides_task_inner(project_id, page_nums, prototype, run_id)


def _generate_slides_task_inner(project_id: str, page_nums: list = None, prototype: bool = False, run_id: str = None):
    """Celery task body with provider credentials installed in context."""
    target_pages = _resolve_target_pages(project_id, page_nums)
    if not target_pages:
        logger.warning(f"No pages to generate for project {project_id}")
        db = SessionLocal()
        try:
            finish_run(db, run_id, status="stale", message="没有可生成的页面", error_msg="no_pages")
            db.commit()
        finally:
            db.close()
        return {"project_id": project_id, "status": "skipped", "reason": "no_pages"}

    # 尝试获取每页的锁，只锁住没被其他任务占用的页
    acquired_pages = _acquire_page_locks(project_id, target_pages)
    if not acquired_pages:
        logger.info(f"All target pages for project {project_id} are already being generated")
        _cleanup_stale_generating_slides(project_id, target_pages)
        db = SessionLocal()
        try:
            finish_run(db, run_id, status="stale", message="所有目标页面都已被其他任务锁定", error_msg="all_pages_locked")
            db.commit()
        finally:
            db.close()
        return {"project_id": project_id, "status": "skipped", "reason": "all_pages_locked"}

    skipped_pages = [p for p in target_pages if p not in acquired_pages]
    if skipped_pages:
        logger.info(f"Skipping locked pages: {skipped_pages}")
        _cleanup_stale_generating_slides(project_id, skipped_pages)

    db = SessionLocal()
    try:
        logger.info(f"Celery task started: project={project_id}, pages={acquired_pages}, prototype={prototype}")
        mark_run_running(db, run_id, stage="batch_generation", message="图片生成任务已启动")
        db.commit()
        run_generation_pipeline(project_id, db, page_nums=acquired_pages, prototype=prototype, run_id=run_id)
        # 生成完成，设置未读通知提醒用户查看
        project = db.query(Project).filter(Project.id == project_id).first()
        if project:
            project.has_unread_notification = True
            project.unread_notification_message = "打样完成" if prototype else "图片生成完成"
            db.commit()
        logger.info(f"Celery task completed: project={project_id}")
        return {"project_id": project_id, "status": "completed", "page_nums": acquired_pages, "prototype": prototype, "skipped_pages": skipped_pages}
    except Exception as exc:
        logger.error(f"Celery task failed: {exc}")
        try:
            project = db.query(Project).filter(Project.id == project_id).first()
            if project:
                has_any_completed = db.query(Slide).filter(
                    Slide.project_id == project_id, Slide.status == "completed"
                ).count() > 0
                if not has_any_completed:
                    project.status = "failed"
                else:
                    # 部分完成 → 回到 prompt_ready，用户可重试失败页
                    project.status = "prompt_ready"
                finish_run(db, run_id, status="failed", message="图片生成任务失败", error_msg=str(exc)[:500])
                db.commit()
        except Exception as cleanup_err:
            logger.warning(f"Failed to update project status after task error: {cleanup_err}")
        return {"project_id": project_id, "status": "failed", "error": str(exc), "page_nums": acquired_pages, "prototype": prototype}
    finally:
        _release_page_locks(project_id, acquired_pages)
        redis_client.delete(f"project:{project_id}:task_id")
        redis_client.delete(f"project:{project_id}:task_started_at")
        db.close()


@celery_app.task(bind=True, max_retries=2)
def generate_style_proposals_task(self, project_id: str, run_id: str = None, credential_id: str = None):
    """Celery task: 生成风格提案。"""
    credentials = load_task_provider_credentials(redis_client, credential_id)
    with provider_credentials_context(credentials):
        return _generate_style_proposals_task_inner(self, project_id, run_id)


def _generate_style_proposals_task_inner(self, project_id: str, run_id: str = None):
    """Style proposal task body with provider credentials installed in context."""
    db = SessionLocal()
    try:
        logger.info(f"[StyleProposals Celery] Starting for project={project_id}")
        project = db.query(Project).filter(Project.id == project_id).first()
        if not project:
            logger.warning(f"[StyleProposals Celery] Project not found: {project_id}")
            finish_run(db, run_id, status="failed", message="项目不存在", error_msg="project_not_found")
            db.commit()
            return {"project_id": project_id, "status": "not_found"}

        slides = db.query(Slide).filter(Slide.project_id == project_id).order_by(Slide.page_num).all()
        if not slides:
            logger.warning(f"[StyleProposals Celery] No slides found for project: {project_id}")
            finish_run(db, run_id, status="failed", message="没有内容规划页面", error_msg="no_slides")
            db.commit()
            return {"project_id": project_id, "status": "no_slides"}

        mark_run_running(db, run_id, stage="style_proposal", message="正在生成风格提案...")
        db.commit()

        content_plan = [s.content_json for s in slides]

        # 自动分析项目素材（失败不阻断主流程）
        assets = {}
        if project.reference_images:
            logo_refs = [r for r in project.reference_images if r.role == "logo"]
            style_refs = [r for r in project.reference_images if r.role == "style_ref"]
            template_refs = [r for r in project.reference_images if r.role == "template"]

            if logo_refs:
                try:
                    logger.info(f"[StyleProposals Celery] Analyzing logo for project={project_id}")
                    assets["logo_analysis"] = analyze_logo(logo_refs[0].file_path)
                except Exception as e:
                    logger.warning(f"[StyleProposals Celery] Logo analysis failed: {e}")

            if style_refs:
                existing_style_refs = [r for r in style_refs if os.path.exists(r.file_path)]
                if not existing_style_refs:
                    msg = "已上传风格参考图，但原文件不存在。请重新上传参考图后再生成风格提案。"
                    finish_run(db, run_id, status="failed", message=msg, error_msg="style_reference_file_missing")
                    project.style_proposal = None
                    db.commit()
                    return {"project_id": project_id, "status": "failed", "error": "style_reference_file_missing"}
                try:
                    logger.info(f"[StyleProposals Celery] Analyzing reference image for project={project_id}")
                    assets["reference_analysis"] = analyze_reference_image(existing_style_refs[0].file_path)
                except Exception as e:
                    logger.warning(f"[StyleProposals Celery] Reference analysis failed: {e}")

            if template_refs or project.selected_template_recommendations:
                assets["template_analysis"] = {"has_template": True}
                template_sample = None
                recommendations = project.selected_template_recommendations or {}
                if isinstance(recommendations, dict):
                    for key in ("cover", "content", "toc", "ending"):
                        rec = recommendations.get(key)
                        if isinstance(rec, dict) and rec.get("file_path"):
                            template_sample = rec["file_path"]
                            break
                if not template_sample and template_refs:
                    template_sample = template_refs[0].file_path
                if template_sample:
                    try:
                        logger.info(f"[StyleProposals Celery] Analyzing template reference for project={project_id}")
                        assets["template_analysis"]["reference_analysis"] = analyze_reference_image(template_sample)
                    except Exception as e:
                        logger.warning(f"[StyleProposals Celery] Template analysis failed: {e}")

        proposals = generate_style_proposals(content_plan, assets=assets if assets else None)
        db.expire_all()
        if not is_run_active(db, run_id):
            logger.info(f"[StyleProposals Celery] Run {run_id} is no longer active; skipping stale writeback")
            return {"project_id": project_id, "status": "stale"}
        project = db.query(Project).filter(Project.id == project_id).first()
        if not project:
            finish_run(db, run_id, status="failed", message="项目不存在", error_msg="project_not_found")
            db.commit()
            return {"project_id": project_id, "status": "not_found"}
        asset_based = any(
            p.get("source") == "asset_clone" or p.get("clone_mode") == "strict_reference"
            for p in proposals
            if isinstance(p, dict)
        )
        update_run_progress(db, run_id, completed_count=len(proposals), total_count=len(proposals), message="正在保存风格提案...")
        project.style_proposal = {
            "proposals": proposals,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "asset_based": asset_based,
            "asset_signature": compute_style_asset_signature(project),
        }
        # 风格提案生成后，项目进入视觉方案待确认阶段
        if project.status in ("planning", "draft"):
            project.status = "visual_ready"
        project.content_plan_confirmed = True
        finish_run(
            db,
            run_id,
            status="succeeded",
            message=f"风格提案已生成，共 {len(proposals)} 套",
            completed_count=len(proposals),
        )
        # 风格提案生成完成，设置未读通知
        project.has_unread_notification = True
        project.unread_notification_message = "风格提案已生成"
        db.commit()
        logger.info(f"[StyleProposals Celery] Completed for project={project_id}, count={len(proposals)}, asset_based={asset_based}")
        return {"project_id": project_id, "status": "completed", "proposals_count": len(proposals), "asset_based": asset_based}
    except Exception as exc:
        db.rollback()
        logger.error(f"[StyleProposals Celery] Failed for project={project_id}: {exc}")
        if self.request.retries >= self.max_retries:
            # 重试已用完，标记项目失败，避免前端永远轮询
            try:
                project = db.query(Project).filter(Project.id == project_id).first()
                if project:
                    project.status = "failed"
                    finish_run(db, run_id, status="failed", message="风格提案生成失败", error_msg=str(exc)[:500])
                    db.commit()
                    logger.info(f"[StyleProposals Celery] Marked project={project_id} as failed after max retries")
            except Exception as mark_err:
                logger.warning(f"[StyleProposals Celery] Failed to mark project failed: {mark_err}")
            raise
        raise self.retry(exc=exc, countdown=15)
    finally:
        db.close()
